### ISSUE TITLE
Windows 8 client constantly uses 25% of quad core system (i.e. 100% 1 core)

### ISSUE THREAD

**Issue by haimiko** [owncloud-archive/windows8#6]
OS: Windows 8.1 64bit 
I've been experiencing, throughout all previous and the latest release, consistent abnormal CPU utilization by the windows 8 client.  Owncloud is always at the top of the CPU sort list @ 25% of a quad core system (or 100% of one core)..   Even when there are no active file synchronizations taking place.  I assume it's because owncloud is polling the server, checking for changes.  As you can see from the second image, in total, owncloud is using very close to 50% of it's total time up.
Is there anything that can be done to throttle this?

![image](https://cloud.githubusercontent.com/assets/3318870/4887047/67d541de-6381-11e4-8bd5-ba0d420889d8.png)

![image](https://cloud.githubusercontent.com/assets/3318870/4887073/abb1a69a-6381-11e4-82f8-3222a175b30f.png)

**Comment by LukasReschke** [comment]
I think you're talking about the desktop client?

If so please reopen the issue at https://github.com/owncloud/mirall
